name: Build Spring Boot Application

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven


      - name: Build Application
        run: mvn clean package -DskipTests


      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: springboot-application-jar
          path: target/*.jar
          retention-days: 30
